services:
  - type: web
    name: mbank-final
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: GROQ_MODEL
        value: groq/compound
      - key: GROQ_API_KEY
        sync: false
